https://stackoverflow.com/questions/27483694/how-to-create-custom-post-type-item-by-submitting-form-on-frontend-in-wordpress
https://code.tutsplus.com/tutorials/posting-via-the-front-end-inserting--wp-27034
https://stackoverflow.com/questions/21457332/submitting-a-form-on-a-custom-admin-page-in-wordpress

wordpress stupidness
http://codex.wordpress.org/Using_Custom_Fields
http://blog.materialgirlcollection.com/socialize/
http://www.google.com/#q=wordpress+single+image&hl=en&safe=off&ei=bo4aTJW2BsGqlAeg5O3BBQ&start=10&sa=N&fp=c4f763afdc45574d
http://bavotasan.com/downloads/simple-image-grabber-wordpress-plugin/
http://www.google.com/#hl=en&safe=off&q=get+wordpress+page+content&aq=9m&aqi=g8g-m2&aql=&oq=wordpress+page+cont&gs_rfai=&fp=c4f763afdc45574d
http://www.snilesh.com/resources/wordpress/wordpress-hacks-and-tricks/wordpress-get-page-content-by-page-id/
http://codex.wordpress.org/Function_Reference/get_page
http://www.tanzilo.com/2008/12/19/wordpress-get-page-id-and-content-with-example-code/
http://codex.wordpress.org/Template_Tags/wp_list_categories
http://wordpress.org/extend/plugins/wordpress-social-login/
http://wordpress.org/support/topic/how-to-create-rss-feed-that-includes-multiple-categories
http://wordpress.org/extend/plugins/html-emails/other_notes/
http://blog.avtex.com/2012/03/14/creating-dynamic-html-e-mail-templates-in-wordpress/
http://wordpress.org/extend/plugins/more-fields/
http://wordpress.org/extend/plugins/more-types/
http://www.elliotcondon.com/using-the-advanced-custom-fields-plugin-to-create-a-custom-home-page-in-wordpress/
http://www.advancedcustomfields.com/resources/getting-started/displaying-custom-field-values-in-your-theme/
http://wpguy.com/articles/an-archives-page-with-all-the-posts-in-cronological-order/
http://codex.wordpress.org/Function_Reference/get_query_var
https://api.wordpress.org/secret-key/1.1/salt/
https://gist.github.com/ninnypants/1668216
https://wordpress.org/plugins/shortcode-empty-paragraph-fix/installation/
http://infographic.city/wordpress-cheat-sheet/
http://css-tricks.com/snippets/wordpress/remove-paragraph-tags-from-around-images/
http://wordpress.stackexchange.com/questions/1567/best-collection-of-code-for-your-functions-php-file
https://github.com/WebDevStudios/CMB2
http://code.tutsplus.com/articles/unraveling-the-secrets-of-wordpress-commentsphp-file--net-28
http://thewebtaylor.com/articles/wordpress-creating-breadcrumbs-without-a-plugin
https://mondaybynoon.com/wordpress-widget-image-field/
http://stackoverflow.com/questions/13863087/wordpress-custom-widget-image-upload
https://codex.wordpress.org/TinyMCE_Custom_Buttons
http://wordpress.stackexchange.com/questions/72394/how-to-add-a-shortcode-button-to-the-tinymce-editor
http://www.smashingmagazine.com/2012/11/complete-guide-custom-post-types/
https://developer.wordpress.org/resource/dashicons/#list-view
https://wordpress.org/plugins/simple-share-buttons-adder/screenshots/
http://wordpress.stackexchange.com/questions/141125/allow-html-in-excerpt
https://github.com/taniarascia/wp-functions
http://ethanellis.com/wordpress-reset-functions-php/
http://www.wpbeginner.com/wp-tutorials/9-most-useful-htaccess-tricks-for-wordpress/
https://codex.wordpress.org/Creating_Options_Pages
https://codex.wordpress.org/Child_Themes#Creating_a_Child_Theme_from_an_Unmodified_Parent_Theme
https://code.tutsplus.com/tutorials/how-to-create-custom-wordpress-writemeta-boxes--wp-20336
https://codex.wordpress.org/Creating_Options_Pages
http://smallenvelop.com/limit-post-excerpt-length-in-wordpress/
https://neliosoftware.com/blog/how-to-upload-additional-file-types-in-wordpress/
https://themefoundation.com/wordpress-meta-boxes-guide/
https://codex.wordpress.org/Function_Reference/wp_editor
https://codex.wordpress.org/Hardening_WordPress
https://wordpress.stackexchange.com/questions/137583/how-to-safely-sanitize-a-textarea-which-takes-full-html-input
https://codex.wordpress.org/Function_Reference/has_shortcode
https://wordpress.stackexchange.com/questions/168524/how-to-use-wordpress-color-picker-api-in-custom-post-type-metabox
https://www.google.com/search?q=wordpress+search+custom+post+type&ie=utf-8&oe=utf-8
http://wpsnipp.com/index.php/functions-php/add-media-library-column-with-image-width-and-height-wp_get_attachment_metadata/
https://codex.wordpress.org/Theme_Development#Template_Files
https://kunaldesai.blog/remove-junk-wordpress-head/
http://tgmpluginactivation.com/installation/
https://www.keycdn.com/support/remove-query-strings-from-static-resources/